### ISSUE TITLE
Support addEventListener options param

### ISSUE THREAD

**Issue by natefaubion** [purescript-web/purescript-web-events#8]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by garyb** [comment]
Pretty sure that wasn't in the DOM4 standard, but it seems that the URI for that redirects to the DOM living standard now anyway. 🤔

**Comment by i-am-the-slime** [comment]
Would you consider a contribution with this? The random `Boolean` parameter is a bit ugly anyway. I'm not sure how you would suggest to make this backwards-compatible, though.
